[[statemachine-getting-started]]
= Getting started

만약 당신이 지금 방금 Spring Statemachine을 시작했다면, 이것은 당신을 위한 섹션이다!
여기서 우리는 기본적인 “`what?`”, “`how?`” 그리고 “`why?`” 물음에 대해 답할 것이다.
우리는 부드럽게 Spring Statemachine에 대해 소개를 시작한다.
그리고 우리는 첫 Spring Statemachine application을 빌드하고 우리가 가지는 핵심 원칙에 대해 다룰 것이다.

== System Requirement

Spring Statemachine {revnumber} 은 JDK 8과 Sprinf Framework {spring-version} 에서 빌드/테스트 되었다. (모든 artifact는 JDK 7 호환성이 있다.)
그것의 core system에는 Spring Framework 외의 어떠한 의존성도 요구하지 않는다.

다른 부가적인 파트 (such as <<sm-distributed>>) 는 <<statemachine-examples>> 이 자체적으로 
framework를 넘어서 다른 의존성을 가져오는 `spring-shell` 과 `spring-boot` 을 사용함으로써 Zookeeper에 의존성이 있다.
또한, 부가적인 security와 data 접근 기능은 Spring Security와 Spring Data 모듈에 의존성이 있다.

== Modules

아래 표는 Spring Statemachine에서 사용 가능한 모듈이다.

|===
|Module |Description

|`spring-statemachine-core`
|The core system of Spring Statemachine.

|`spring-statemachine-recipes-common`
|Common recipes that do not require dependencies outside of the core
framework.

|`spring-statemachine-kryo`
|`Kryo` serializers for Spring Statemachine.

|`spring-statemachine-data-common`
|Common support module for `Spring Data`.

|`spring-statemachine-data-jpa`
|Support module for `Spring Data JPA`.

|`spring-statemachine-data-redis`
|Support module for `Spring Data Redis`.

|`spring-statemachine-data-mongodb`
|Support module for `Spring Data MongoDB`.

|`spring-statemachine-zookeeper`
|Zookeeper integration for a distributed state machine.

|`spring-statemachine-test`
|Support module for state machine testing.

|`spring-statemachine-cluster`
|Support module for Spring Cloud Cluster.
Note that Spring Cloud Cluster has been superseded by Spring Integration.

|`spring-statemachine-uml`
|Support module for UI UML modeling with Eclipse Papyrus.

|`spring-statemachine-autoconfigure`
|Support module for Spring Boot.

|`spring-statemachine-bom`
|Bill of Materials pom.

|`spring-statemachine-starter`
|Spring Boot starter.
|===

== Using Gradle

아래 리스트는 https://start.spring.io에서 설정했을 때 만들어지는 `build.gradle` 을 보여준다.:

====
[source,groovy,indent=0,subs="attributes+"]
----
buildscript {
	ext {
		springBootVersion = '{spring-boot-version}'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
}


ext {
	springStatemachineVersion = '{revnumber}'
}

dependencies {
	compile('org.springframework.statemachine:spring-statemachine-starter')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.statemachine:spring-statemachine-bom:${springStatemachineVersion}"
	}
}
----
====

IMPORTANT: `0.0.1-SNAPSHOT`를 원하는 버전으로 바꿔라.

일반적인 프로젝트 구조라면, 당신은 이 프로젝트를 아래 명령어로 빌드할 수 있다.:

====
[source,text,indent=0]
----
# ./gradlew clean build
----
====

예상되는 Spring Boot-packaged fat jar는 `build/libs/demo-0.0.1-SNAPSHOT.jar`이다.

NOTE: production 개발에는 `libs-milestone` 와 `libs-snapshot` 리파지토리는 필요하지 않다.

== Using Maven

아래 예는 https://start.spring.io에서 설정했을 때 만들어지는 일반적인 `pom.xml` 파일이다.:

====
[source,xml,indent=0,subs="attributes+"]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>gs-statemachine</name>
	<description>Demo project for Spring Statemachine</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>{spring-boot-version}</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-statemachine.version>{revnumber}</spring-statemachine.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.statemachine</groupId>
			<artifactId>spring-statemachine-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.statemachine</groupId>
				<artifactId>spring-statemachine-bom</artifactId>
				<version>${spring-statemachine.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>


</project>
----
====

IMPORTANT: `0.0.1-SNAPSHOT`를 원하는 버전으로 바꿔라.

일반적인 프로젝트 구조라면, 당신은 이 프로젝트를 아래 명령어로 빌드할 수 있다.:

====
[source,text,indent=0]
----
# mvn clean package
----
====

예상되는 Spring Boot-packaged fat jar는 `target/demo-0.0.1-SNAPSHOT.jar`이다.

NOTE: production 개발에는 `libs-milestone` 와 `libs-snapshot` 리파지토리는 필요하지 않다.

==  Developing Your First Spring Statemachine Application

당신은 `CommandLineRunner`를 구현하는 간단한 Spring Boot `Application` class를 생성해서 시작할 수 있다.
아래 예는 어떻게 하는지를 보여준다.:

====
[source,java,indent=0]
----
@SpringBootApplication
public class Application implements CommandLineRunner {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
----
====

그리고 당신은 아래 예제처럼 states와 events를 추가할 필요가 있다.:

====
[source,java,indent=0]
----
public enum States {
    SI, S1, S2
}

public enum Events {
    E1, E2
}
----
====

그리고 당신은 아래 예제처럼 state machine 설정을 추가할 필요가 있다.:

====
[source,java,indent=0]
----
@Configuration
@EnableStateMachine
public class StateMachineConfig
        extends EnumStateMachineConfigurerAdapter<States, Events> {

    @Override
    public void configure(StateMachineConfigurationConfigurer<States, Events> config)
            throws Exception {
        config
            .withConfiguration()
                .autoStartup(true)
                .listener(listener());
    }

    @Override
    public void configure(StateMachineStateConfigurer<States, Events> states)
            throws Exception {
        states
            .withStates()
                .initial(States.SI)
                    .states(EnumSet.allOf(States.class));
    }

    @Override
    public void configure(StateMachineTransitionConfigurer<States, Events> transitions)
            throws Exception {
        transitions
            .withExternal()
                .source(States.SI).target(States.S1).event(Events.E1)
                .and()
            .withExternal()
                .source(States.S1).target(States.S2).event(Events.E2);
    }

    @Bean
    public StateMachineListener<States, Events> listener() {
        return new StateMachineListenerAdapter<States, Events>() {
            @Override
            public void stateChanged(State<States, Events> from, State<States, Events> to) {
                System.out.println("State change to " + to.getId());
            }
        };
    }
}
----
====

그리고 당신은 `CommandLineRunner`를 구현하고 `StateMachine`를 주입받을 필요가 있다.
아래 예제는 어떻게 하는지를 보여준다.:

====
[source,java,indent=0]
----
@Autowired
private StateMachine<States, Events> stateMachine;

@Override
public void run(String... args) throws Exception {
    stateMachine.sendEvent(Events.E1);
    stateMachine.sendEvent(Events.E2);
}
----
====

당신이 application을 `Gradle` 이나 `Maven`으로 빌드하느냐에 따라, 
각각 당신은 `java -jar build/libs/gs-statemachine-0.1.0.jar` 또는 `java -jar target/gs-statemachine-0.1.0.jar`로 실행할 수 있다.

이 명령어의 출력은 일반적인 Spring Boot의 것이어야 한다.
그러나, 당신은 아래 lines을 찾아야만 한다.:

====
[source,text,indent=0]
----
State change to SI
State change to S1
State change to S2
----
====

이 line들은 당신이 만든 machine이 하나의 상태에서 다른 상태로 이동하는 것을 나타낸다.
