[[introduction]]
= Introduction

Spring Statemachine (SSM)은 application 개발자가 전통적인 state machine 컨셉을
Spring application과 함께 사용할 수 있게 해주는 framework이다.
SSM은 다음과 같은 기능을 제공한다:

* 간단한 use case에 flat (one-level)의 사용하기 쉬운 state machine.
* 복잡한 state 설정을 쉽게 하는 계층적인 state machine 구조.
* 보다 복잡한 state 설정을 제공하는 state machine regions.
* triggers, transitions, guards, and actions의 사용.
* Type-safe한 설정 adopter.
* State machine event listeners.
* state machine과 bean을 연관시키기 위한 Spring IoC integration.

시작하기 전에, 우리는 당신이 state machines이 무엇인지 일반적인 개념을 잡기 위해
부록 <<glossary>>와 <<crashcourse>>를 보기를 추천한다.
나머지 문서들은 당신이 state machine 컨셉에 익숙하다고 가정한다.

== Background

State machines는 그것의 행동이 항상에 일관되는 것을 보장하고,
machine이 시작될 때 그것이 어떻게 동작할 것인지 규칙이 정해져서 비교적 디버깅이 쉽기 때문에 강력하다.
아이디어는 당신의 application이 유한한 state에 존재한다는 것이다.
그리고 무슨 일이 일어나면 당신의 application은 하나의 상태에서 다음 상태로 넘어간다.
하나의 state machine은 evnets 또는 timers에 기반한 trigger에 의해 구동된다.

application 외부에 high-level의 로직을 설계하고, state machine과 다양한 방법으로 소통하는 것은 훨씬 쉽다.
당신은 events를 보내고, state machine이 무엇을 하는지 listening하고, 현재 state에 대해 요청함으로써 state machine과 소통할 수 있다.

전통적으로, state machine은 개발자가 코드가 스파게티 코드처럼 보이기 시작한 것을 인지했을 때 이미 존재하는 프로젝트에 추가되었다.
스파게티 코드는 절대 끝나지 않을 것처럼 보이고, 계층적인 IF/ELSE/BREAK 구문이 있고,
그리고 아마 무언가 매우 복잡해보이기 시작할 때 컴파일러가 개발자에게 집에가라고 물어본다.

== Usage Scenarios

state machine을 사용하기 좋은 project:

* 당신이 application이나 그것의 일부 구조를 states로 표현할 수 있다.
* 당신이 복잡한 로직을 작고 관리할 수 있는 task들로 나누고 싶다.
* application이 이미 무언가 비동기로 이루어지는 것과 같은 동시성 이슈로 고통받고 있다.

당신이 아래처럼 하고 있다면 이미 state machine을 구현하기를 시도하고 있다:

* model 상태를 위해 boolean flags나 enums을 사용한다.
* 오직 application 라이프사이클의 특정 부분을 위한 의미만을 가지는 변수가 있다.
* 특정 flag나 enum이 설정되었는지 체크하고, 당신의 flag나 enum이 특정 조합일 경우 무엇을 하거나 또는 없다면 exception을 발생시키는 if-else 구문을 포함하는 반복문(또는 더 나쁘다면, multiple such 구조)이 있다.
 