[[sm-config]]
== Statemachine Configuration

state machine을 사용할 때 일반적인 작업 중 하나는 그것의 runtime 설정을 설계하는 것이다. 
이 챕터는 Spring Statemachine이 어떻게 설정되고, 그리고 그것이 관리가 편리하게 하기 위해 Application 내부를 간단하게 하려고
Spring의 가벼운 IoC 컨테이너를 어떻게 이용했는지에 초점을 맞춘다.

NOTE: 이 섹션의 예제는 완전하지 않다. 당신은 항상 state와 transition 둘 모두의 정의를 가지고 있을 필요가 있다.
그렇지 않으면, state machine 설정을 잘못된 형식일 수 있다. 우리는 다른 부분이 필요로 하는 부분은 제거하여 code snippet을 간단하게 만들었다.

[[statemachine-config-annotations]]
=== Using `enable` Annotations

우리는 간편한 설정을 위해 Spring의 두가지 친숙한 _enabler_ 어노테이션을 사용한다.: `@EnableStateMachine` and `@EnableStateMachineFactory`.
이 어노테이션들은 @Configuration 클래스 안에 사용될 경우 state machine이 필요로 하는 몇가지 기본 기능을 활성화시킨다.

당신은 하나의 StateMachine 인스턴스가 필요할 때 @EnableStateMachine 을 사용할 수 있다.
일반적으로, @Configuration 클래스는 당신이 configuration callback 메소드 를 override 할 수 있는 adapter(EnumStateMachineConfigurerAdapter or StateMachineConfigurerAdapter)를 확장한다.
우리는 당신이 이 adapter 클래스를 사용하고 runtime 설정 로직을 수정한 것을 자동으로 탐지한다.

당신은 `StateMachineFactory` 인스턴스를 생성하는 설정이 필요할 때 `@EnableStateMachineFactory` 을 사용할 수 있다.

NOTE: 이 예제의 사용법은 아래 섹션에 있다.

[[statemachine-config-states]]
=== Configuring States

우리는 이 가이드 중간에 좀 더 복잡한 설정 예제를 본다. 그러나 우리는 우선 간단한 것으로 시작한다.
대부분의 간단한 state machine에서 당신은 `EnumStateMachineConfigurerAdapter` 을 사용할 수 있고, 가능한 state와 초기상태와 부가적인 종료상태를 정의할 수 있다.

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetAA]
----
====

당신은 다음예제에서 보듯이 `StateMachineConfigurerAdapter` 을 사용해서 state와 event에 enumerations 대신에 string을 사용할 수 있다.
대부분의 설정 예제는 enumerations을 사용하지만, 일반적으로 말하면 당신은 strings 과 enumerations 간에 바꿔서 할 수 있다.

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetAB]
----
====

NOTE: enumerations 사용은 state와 event 를 type safe 하게 설정할 수 있다. 하지만 가능한 조합을 컴파일 타임에 제한된다.
String은 이러한 제한이 없어 당신이 더 자유로운 방식으로 state machine을 설정할 수 있게 한다. 하지만 같은 레벨의 safety는 허용하지 않는다.

=== Configuring Hierarchical States

당신은 다수의 `withStates()` 호출로 계층적인 state를 정의할 수 있다. 당신은 `parent()` 를 사용해서 이 특별한 state는 다른 state의 sub-state 임을 가리킬 수 있다.
다음의 예제는 그것을 어떻게 하는지 이다.:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetB]
----
====

=== Configuring Regions

state 의 콜랙션이 직교상태의 부분임을 표시하는 특별한 설정은 없다. 간단하게, 직교상태는 동일한 계층 state machine이 여러 개의 각각의 초기 상태를 가지는 state 세트를 가질 때 생성된다.
각각의 state machine은 오직 하나의 초기 상태만 가질 수 있기 때문에 여러개의 초기 state는 반드시 특정한 statem는 독립된 각각의 region을 갖아야 함을 의미한다. 
다음의 얘제는 region을 어떻게 정의하는지 이다.:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetP]
----
====

machine을 region과 함께 저장하거나 일반적으로 machine을 reset하는 어떤 기능에 의지한다면, 당신은 region에 dedicated ID를 갖어야 한다.
기본적으로 이 ID는 생성된 UUID이다. 다음 예제가 보여주듯이, `StateConfigurer` 는 region에 ID를 셋팅하는 `region(String id)` 라는 메소드가 있다.

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetPP]
----
====

=== Configuring Transitions

우리는 3가지 다른 타입의 transition을 지원한다.: `external`, `internal`, and `local`.
Transition 은 signal(state machine으로 전달된 event)이나 timer에 의해 트리거된다.
다음 예제는 3가지 타입의 transition을 어떻게 정의하는지 보여준다.:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetC]
----
====

=== Configuring Guards

당신은 state transition을 보호하기 위해 guard를 사용할 수 있다. 당신은 `StateContext` 에 접근하는 메소드에서 비교하기 위해 `Guard` 인터페이스를 사용할 수 있다.
다음 예제는 어떻게 하는지 보여준다.:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetD]
----
====

앞의 예제에서, 우리는 다른 2가지 타입의 guard 설정을 사용했다. 
첫째, 우리는 간단한 `Guard` 를 bean으로 만들고 `S1` 과 `S2` state 사이의 transition 에 붙였다.

둘째, 우리는 SPeL 표현식을 guard로 사용하여 표현식이 `BOOLEAN` 값을 리턴하도록 하였다. 사실 표현식 기반의 guard는 `SpelExpressionGuard` 이다.
우리는 그것을 `S2` 과 `S3` state 사아애 transition에 붙였다. 두개의 guard 모두 항상 `true` 로 평가된다.

[[statemachine-config-actions]]
=== Configuring Actions

당신은 transition과 state와 함께 실행되도록 action을 정의할 수 있다.
트리거되는 transition에 기반하는 action은 trasition의 결과로 항상 실행된다.
다음 예제는 어떻게 action을 정의하는지 보여준다.:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetEA]
----
====

앞의 예제에서 단일 `Action` 이 `action` 이라는 이름의 bean으로 정의되고 `S1` 에서 `S2` 로의 transition에 연관되었다.
다음 예제는 어떻게 하나의 action을 여러번 사용하는지 보여준다.:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetEB]
----
====

NOTE: 보통 당신은 동일한 `Action` 인스턴스를 다른 stage에 정의하지 않는다. 그러나 우리는 code snippet을 복잡하지 않게 하려고 그렇게 했다.

앞의 예제에서 단일 `Action` 이 `action` 이라는 이름의 bean으로 정의되고 `S1`, `S2`, 그리고 `S3` 상태와 연관되었다.
우리는 여기서 무슨일이 일어나고 있는지 분명히 해야 한다.:

* 우리는 초기상태인 `S1` 을 위해 하나의 action을 정의했다.
* 우리는 `S1` 상태에 entry action을 정의했고 exit action은 비워두었다.
* 우리는 `S2` 상태에 exit action을 정의했고 entry action은 비워두었다.
* 우리는 `S2` 상태에 단일 state action을 정의했다.
* 우리는 `S3` 상태에 entry action과 exit action 둘다 정의했다.
* `S1` 은 `initial()` 과 `state()` funtion에서 두번 사용되었음을 참고해라. 당신은 오직 entry 또는 exit action을 초기 상태에 정의하고 싶을 때만 이렇게 할 필요가 있다.

IMPORTANT: action을 `initial()` function고 함께 정의하는 것은 오직 state machine 또는 sub state 가 시작되는 특별할 때만 실행된다.
이것은 오직 한번만 실행되는 초기화 action이다. `state()` 과 함께 정의된 action은 state machine 이 초기 상태와 초기 상태가 아닌 상태 사이에 transition 될 때 실행된다.

==== State Actions

State action 는 entry 와 exit 를 비교했을 때 다르게 동작한다. 왜냐면 실행은 state가 enter한 이후에 일어나고, 만약 특정 action이 완료되기 전에 state exit가 일어난다면 cancel 될 수 있기 때문이다.

State action 은 Reactor의 기본 병령 스케쥴러를 구독함으로써 일반 reactive flow를 사용하여 실행된다.
이것은 당신이 action에서 뭘하든지 `InterruptedException` 을 catch할 수 있게 하거나, 또는 더 일반적으로는 `Thread` 가 interrupt 되었는지 주기적으로 체크해야 한다.

다음 예제는 state가 완료되었을 때 실행중인 task를 즉시 취소시키는 기본 `IMMEDIATE_CANCEL` 을 사용하는 일반적인 설정을 보여준다.

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests11.java[tags=snippetA]
----
====

당신은 정책을 각 state machine 의 global timeout 과 함께 `TIMEOUT_CANCEL` 으로 설정할 수 있다.
이것은 state의 동작을 cancel 요청이 오기까지 action이 완료되기를 기다리도록 변경한다.
다음 예제는 어떻게 하는지 보여준다.:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests11.java[tags=snippetB]
----
====

If `Event` directly takes a machine into a state so that event headers
are available to a particular action, you can also use a dedicated
event header to set a specific timeout (defined in `millis`).
You can use the reserved header value `StateMachineMessageHeaders.HEADER_DO_ACTION_TIMEOUT`
for this purpose. The following example shows how to do so:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests11.java[tags=snippetC]
----
====

[[statemachine-config-transition-actions-errorhandling]]
==== Transition Action Error Handling

You can always catch exceptions manually. However, with actions defined for
transitions, you can define an error action that is called if an
exception is raised. The exception is then available from a `StateContext`
passed to that action. The following example shows how to create a state
that handles an exception:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetEC]
----
====

If need be, you can manually create imilar logic for every action.
The following example shows how to do so:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetED]
----
====

[[statemachine-config-state-actions-errorhandling]]
==== State Action Error Handling

Logic similar to the logic that handles errors in state transitions is also available
for entry to a state and exit from a state.

For these situations, `StateConfigurer` has methods called `stateEntry`, `stateDo`, and
`stateExit`. These methods define an `error` action together with a normal (non-error) `action`.
The following example shows how to use all three methods:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetEE]
----
====

=== Configuring Pseudo States

_Pseudo state_ configuration is usually done by configuring states and
transitions. Pseudo states are automatically added to state machine as
states.

==== Initial State

You can mark a particular state as initial state by using the `initial()`
method. This initial action is good, for example, to initialize
extended state variables. The following example shows how to use the `initial()` method:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetQ]
----
====

==== Terminate State

You can mark a particular state as being an end state by using the `end()` method.
You can do so at most once for each individual sub-machine or region.
The following example shows how to use the `end()` method:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetAA]
----
====

==== State History

You can define state history once for each individual state machine.
You need to choose its state identifier and set either `History.SHALLOW` or
`History.DEEP`. The following example uses `History.SHALLOW`:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetR]
----
====

Also, as the preceding example shows, you can optionally define a default
transition from a history state into a state vertex in a same machine.
This transition takes place as a default if, for example, the machine has
never been entered -- thus, no history would be available. If a default
state transition is not defined, then normal entry into a region is
done. This default transition is also used if a machine's history is
a final state.

==== Choice State

Choice needs to be defined in both states and transitions to work
properly. You can mark a particular state as being a choice state by using the `choice()`
method. This state needs to match source state when a transition is
configured for this choice.

You can configure a transition by using `withChoice()`, where you define source
state and a `first/then/last` structure, which is equivalent to a normal
`if/elseif/else`. With `first` and `then`, you can specify a guard just
as you would use a condition with `if/elseif` clauses.

A transition needs to be able to exist, so you must make sure to use `last`.
Otherwise, the configuration is ill-formed. The following example shows how to define
a choice state:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetS]
----
====

Actions can be run with both incoming and outgoing transitions of
a choice pseudostate. As the following example shows, one dummy lambda
action is defined that leads into a choice state and one similar dummy
lambda action is defined for one outgoing transition (where it also
defines an error action):

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetSSS]
----
====

NOTE: Junction have same api format meaning actions can be defined
similarly.

[[statemachine-config-states-junction]]
==== Junction State

You need to define a junction in both states and transitions for it to work
properly. You can mark a particular state as being a choice state by using the `junction()`
method. This state needs to match the source state when a transition is
configured for this choice.

You can configure the transition by using `withJunction()` where you define source
state and a `first/then/last` structure (which is equivalent to a normal
`if/elseif/else`). With `first` and `then`, you can specify a guard as
you would use a condition with `if/elseif` clauses.

A transition needs to be able to exist, so you must make sure to use `last`.
Otherwise, the configuration is ill-formed.
The following example uses a junction:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetSS]
----
====

NOTE: The difference between choice and junction is purely academic, as both are
implemented with `first/then/last` structures . However, in theory, based
on UML modeling, `choice` allows only one incoming transition while
`junction` allows multiple incoming transitions. At a code level, the
functionality is pretty much identical.

==== Fork State

You must define a fork in both states and transitions for it to work
properly. You can mark a particular state as being a choice state by using the `fork()`
method. This state needs to match source state when a transition is
configured for this fork.

The target state needs to be a super state or an immediate state in a
regions. Using a super state as a target takes all regions into
initial states. Targeting individual state gives more controlled entry
into regions. The following example uses a fork:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetT]
----
====

==== Join State

You must define a join in both states and transitions for it to work
properly. You can mark aparticular state as being a choice state by using the `join()`
method. This state does not need to match either source states or a
target state in a transition configuration.

You can select a target state where a transition goes when all source states
have been joined. If you use state hosting regions as the source, the end
states of a region are used as joins. Otherwise, you can pick any
states from a region. The following exmaple uses a join:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetU]
----
====

You can also have multiple transitions originate from a
join state. It this case, we advise you to use guards and define your guards
such that only one guard evaluates to `TRUE` at any given time. Otherwise,
transition behavior is not predictable. This is shown in the following example, where the guard
checks whwther the extended state has variables:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetUUU]
----
====

[[statemachine-config-states-exitentry]]
==== Exit and Entry Point States

You can use exit and entry points to do more controlled exit and entry
from and into a submachine.
The following example uses the `withEntry` and `withExit` methods to define entry points:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetUU]
----
====

As shown in the preceding, you need to mark particular states as being `exit` and
`entry` states. Then you create a normal transitions into those states
and also specify `withExit()` and `withEntry()`, where those states
exit and entry respectively.

[[statemachine-config-commonsettings]]
=== Configuring Common Settings

You can set part of a common state machine configuration by using
`ConfigurationConfigurer`. With it you can set `BeanFactory` and an autostart flag
for a state machine. It also lets you register `StateMachineListener` instances,
configure transition conflict policy and region execution policy.
The following example shows how to use `ConfigurationConfigurer`:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetYA]
----
====

By default, the state machine `autoStartup` flag is disabled, because all
instances that handle sub-states are controlled by the state machine itself
and cannot be automatically started. Also, it is much safer to leave
whether a machine should be started
automatically or not to the user. This flag controls only the autostart of a
top-level state machine.

Setting `machineId` within a configuration class is simply a convenience for those times when
you want or need to do it there.

Registering `StateMachineListener` instances is also partly for
convenience but is required if you want to catch a callback during a
state machine lifecycle, such as getting notified of a state machine's
start and stop events. Note that you cannot listen a state
machine's start events if `autoStartup` is enabled, unless you register a listener
during a configuration phase.

You can use `transitionConflictPolicy` when multiple
transition paths could be selected. One usual use case for this is when a
machine contains anonymous transitions that lead out from a sub-state
and a parent state and you want to define a policy in which one is
selected. This is a global setting within a machine instance and
defaults to `CHILD`.

You can use `withDistributed()` to configure `DistributedStateMachine`. It
lets you set a `StateMachineEnsemble`, which (if it exists) automatically
wraps any created `StateMachine` with `DistributedStateMachine` and
enables distributed mode. The following example shows how to use it:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetYB]
----
====

For more about distributed states, see <<sm-distributed>>.

The `StateMachineModelVerifier` interface is used internally to
do some sanity checks for a state machine's structure. Its purpose is to
fail fast early instead of letting common configuration errors into a
state machine. By default, a verifier is automatically enabled and the
`DefaultStateMachineModelVerifier` implementation is used.

With `withVerifier()`, you can disable verifier or set a custom one if
needed. The following example shows how to do so:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests.java[tags=snippetYC]
----
====

For more about config model, see <<devdocs-configmodel>>.

NOTE: The `withSecurity`, `withMonitoring` and `withPersistence` configuration methods
are documented in <<sm-security>>, <<sm-monitoring>>, and
<<sm-persist-statemachineruntimepersister>>, respectively.

=== Configuring Model

`StateMachineModelFactory` is a hook that lets you configure a statemachine model
without using a manual configuration. Essentially, it is a third-party
integration to integrate into a configuration model.
You can hook `StateMachineModelFactory` into a configuration model by
using a `StateMachineModelConfigurer`. The following example shows how to do so:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests8.java[tags=snippetA]
----
====

The follwoing example uses `CustomStateMachineModelFactory` to
define two states (`S1` and `S2`) and an event (`E1`) between those
states:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests8.java[tags=snippetB]
----
====

NOTE: Defining a custom model is usually not what people are looking for,
although it is possible. However, it is a central concept of allowing
external access to this configuration model.

You can find an example of using this model factory integration in
<<sm-papyrus>>. You can find more generic info about custom model integration
in <<devdocs>>.

[[statemachine-config-thingstoremember]]
=== Things to Remember

When defining actions, guards, or any other references from a
configuration, it pays to remember how Spring Framework works
with beans. In the next example, we have defined a normal configuration with
states `S1` and `S2` and four transitions between those. All transitions
are guarded by either `guard1` or `guard2`. You must ensure that
`guard1` is created as a real bean because it is annotated with
`@Bean`, while `guard2` is not.

This means that event `E3` would get the `guard2` condition as
`TRUE`, and `E4` would get the `guard2` condition as `FALSE`, because those are
coming from plain method calls to those functions.

However, because `guard1` is defined as a `@Bean`, it is proxied by the
Spring Framework. Thus, additional calls to its method result in
only one instantiation of that instance. Event `E1` would first get the
proxied instance with condition `TRUE`, while event `E2` would get the same
instance with `TRUE` condition when the method call was defined with
`FALSE`. This is not a Spring State Machine-specific behavior. Rather, it is
how Spring Framework works with beans.
The following example shows how this arrangement works:

====
[source,java,indent=0]
----
include::samples/DocsConfigurationSampleTests7.java[tags=snippetA]
----
====
