[[whatsnew]]
= What's New

== In 1.1

Spring Statemachine 1.1은 security와 web application과 더 나은 상호연동에 초점을 두었다.
그것은 다음을 포함한다.:

* 광범위한 Spring Security 지원이 추가되었다. <<sm-security>> 을 참고해라.
* `@WithStateMachine` 로 context integration이 매우 강화되었다. <<sm-context>> 을 참고해라.
* `StateContext` 는 이제 first class citizen이 되어 State Machine과 상호작용합니다. <<sm-statecontext>> 을 참고해라.
* redis built-in 지원과 함께 persistence 관련 기능이 강화되었다. <<sm-persist-redis>>을 참고해라.
* 새로운 기능이 persist 동작을 도와준다. <<sm-persist-statemachinepersister>> 을 참고해라.
* Configuration model class가 이제 public API이다.
* 새로운 timer-based event 기능이 추가되었다.
* 새로운 `Junction` pseudostate. <<statemachine-config-states-junction>> 을 참고해라.
* 새로운 Exit Point와 Entry Point pseudostates. <<statemachine-config-states-exitentry>> 을 참고해라.
* Configuration model 검증.
* 새로운 샘플. <<statemachine-examples-security>> 과 <<statemachine-examples-eventservice>> 을 참고해라.
* Eclipse Papyrus 를 이용하여 UI 모델링을 지원한다. <<sm-papyrus>>을 참고해라.


== In 1.2

Spring Statemachine 1.2는 일반적인 기능 강화에 초점을 맞췄다. 더 나은 UML 지원, 그리고 외부 config repository와의 integration.
그것은 다음을 포함한다.:

* UML sub-machines을 지원한다. <<sm-papyrus-submachineref>> 을 참고해라.
* machine 설정을 외부 repository에 보관하는 새로운 repository 추상화. <<sm-repository>> 을 참고해라.
* 새로운 state actions에 대한 지원. <<state-actions>> 을 참고해라.
* 새로운 transition error action 컨셉. <<statemachine-config-transition-actions-errorhandling>> 을 참고해라.
* 새로운 action error 컨셉. <<statemachine-config-state-actions-errorhandling>> 을 참고해라.
* Spring Boot 지원을 위한 초기화 작업. <<sm-boot>> 을 참고해라.
* tracing 과 monitoring 지원. <<sm-monitoring>> 을 참고해라.


=== In 1.2.8

Spring Statemachine 1.2.8 은 일반적으로 release point에서 보이지 않던 좀더 많은 기능을 포함하고 있다.
그러나 이러한 변경사항들은 Spring Statemachine 1.3 fork에 메리트가 되지는 않는다. 
그것은 다음을 포함한다.:

* JPA entity classes의 테이블 이름이 변경되었다. <<sm-repository-config-jpa>> 을 참고해라.
* 새로운 샘플. <<statemachine-examples-datapersist>> 을 참고해라.
* persistence를 위한 새로운 entity class. <<sm-repository-persistence>> 을 참고해라.
* Transition 충돌 정책. <<statemachine-config-commonsettings>> 을 참고해라.


== In 2.0

Sprinh Statemachine 2.0은 Spring Boot 2.x 지원에 초점을 맞췄다.


=== In 2.0.0

Spring Statemachine 2.0.0 은 다음을 포함한다.:

* monitoring 과 tracing 형식이 변경되었다. <<sm-boot-monitoring>> 을 참고해라.
* `spring-statemachine-boot` module 이 `spring-statemachine-autoconfigure` 로 이름이 변경되었다.


== In 3.0

Spring Statemachine 3.0.0 은 Reactive 지원에 초점을 맞췄다. `2.x` 에서 `3.x` 로 전환하는 것은 
<<appendix-reactormigrationguide>> 에 자세히 설명된 몇가지 주요 변경사항을 소개하는 것이다.

`3.0.x` 에서 우리는 모든 blocking methods 를 deprecated 시켰다. 그것은 미래의 어떤 release 에서 제거될 것이다.


[IMPORTANT]
====
부록 <<appendix-reactormigrationguide>> 을 자세히 읽어봐라. 
우리가 내부적으로 다루지 않는 케이스들을 그것은 `3.x` 으로 마이그레이션 하는 프로세스로 당신을 가이드할 것이다.
====

이 시점에서 문서의 대부분은 reactive interfaces를 보여주기 위해 변경되었다. 
여전히 오래된 blocking methods를 사용하는 사용자들에게 메모를 남깁니다.
